services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
    volumes:
      - ./config/gluetun:/gluetun
      - ./config/gluetun-port-manager:/tmp/gluetun
    environment:
      - VPN_PORT_FORWARDING=on
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Switzerland
      - FIREWALL=on
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORT}},\"current_network_interface\":\"{{VPN_INTERFACE}}\",\"random_port\":false,\"upnp\":false}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080/v1/openvpn/status"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit.rule=${QBIT_DOMAIN}"
      - "traefik.http.routers.qbit.entrypoints=websecure"
      - "traefik.http.routers.qbit.tls=true"
      - "traefik.http.services.qbit.loadbalancer.server.port=8080"


  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ${MEDIA_FOLDER:-./media}/downloads:/downloads
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped


  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/jellyfin:/config
      - ${MEDIA_FOLDER:-./media}:/media
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8096/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=${JELLYFIN_DOMAIN}"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"


  sonarr:
    image: linuxserver/sonarr:4.0.16
    container_name: sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/sonarr:/config
      - ${MEDIA_FOLDER:-./media}/series:/series
      - ${MEDIA_FOLDER:-./media}/downloads:/downloads
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:8989/ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=${SONARR_DOMAIN}"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"


  radarr:
    image: linuxserver/radarr:6.0.4
    container_name: radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/radarr:/config
      - ${MEDIA_FOLDER:-./media}/movies:/movies
      - ${MEDIA_FOLDER:-./media}/downloads:/downloads
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:7878/ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=${RADARR_DOMAIN}"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"


  prowlarr:
    image: linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/prowlarr:/config
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:9696/ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=${PROWLARR_DOMAIN}"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"


  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/bazarr:/config
      - ${MEDIA_FOLDER:-./media}/downloads:/downloads
      - ${MEDIA_FOLDER:-./media}/movies:/movies
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:6767"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
        - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=${BAZARR_DOMAIN}"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

networks:
  traefik:
    name: traefik
    external: true
